Dev
ARQtty/parqser pull request #1
Opened 2021-07-12 21:35 UTC by ARQtty

Please

2021-07-13 06:22 UTC, FrediKats requested changes
Немного хромает объектная модель. Понимание усложняется немного странным неймингом. Например, я бы хотел увидеть более понятное описание, что есть параметры бейз пейджы и компоненты.

2021-07-13 06:22 UTC, FrediKats commented on parqser/LICENSE
> +Copyright (c) 2020 Ilya
2021?

2021-07-13 06:22 UTC, FrediKats commented on parqser/page/base.py
> +        self._parse_results[param_name] = param_value
Метод add_parsed_parameter добавляет что-то в _parse_results. Не очень понятно. Может это должен был быть _parse_parameters?

2021-07-13 06:22 UTC, FrediKats commented on parqser/page/base.py
> +    def add_parsed_parameter(self, param_name: str, param_value: Any):
Возможно, когда ты явно в методе декларируешь , что это add paramenter, то можно не делать префиксы param_name. Если аргументы были name и value, то из контекста можно было бы вывести что это.

2021-07-13 06:22 UTC, FrediKats commented on parqser/parser/base.py
> +class BaseParser:
Хорошая практика, когда имя файла совпадает с именем типа. Не знаю принято ли в питоне такое.

2021-07-13 06:22 UTC, FrediKats commented on parqser/parser/base.py
> +    def parse(self, page: BasePage) -> BasePage:
У теоя есть LoadedPage, что, как мне кажется, какая-то обертка над обработанной страницей. Но при этом ты используешь BasePage для хранения резов.

2021-07-13 06:22 UTC, FrediKats commented on parqser/parser/base.py
> +            page.add_parsed_parameter(component.name, param_value)
А вот тут я уже не понял, что ты таки хочешь хранить внутри.
Но (!) ты модифицируешь объект, что не есть хорошо. Стоит разделять реквест и респонс. Имеет смысл сделать два типа: один тип описывает аргументы (хотя я не уверен, что у тебя есть они помимо source_html) и второй тип, который представляет собой полученную после парсинга информацию.

2021-07-13 06:22 UTC, FrediKats commented on parqser/parser/base.py
> +    @classmethod
Нет единообразия. У тебя этот... Я не знаю как у вас атрибуты называются. Но он используется один раз. Возможно, стоит либо его убрать, либо везде их использовать.

2021-07-13 06:22 UTC, FrediKats commented on parqser/saver/csv.py
> +    def _validate_file_columns(self, path: str, sep: str, columns: List[str]) -> Union[None, List[str]]:
Я так понимаю, буквы платные, а в Тиньке не так хорошо? Ну кинь хоть карту, я тебе задоначу до separator'а.

2021-07-13 06:22 UTC, FrediKats commented on parqser/saver/csv.py
> +        if os.path.exists(path):
Вложенность довольно неприятная. Попробуй в декомпозицию.
```
if len(columns) == 0:
  ....
  return
...
if columns != readen_columns:
  raise AttributeError(f'given columns doesnt match with columns in file {path}')
...

2021-07-13 06:22 UTC, FrediKats commented on parqser/saver/csv.py
> +            if len(columns):
Странная проверка.

2021-07-13 06:22 UTC, FrediKats commented on parqser/saver/csv.py
> +    def __init__(self, path: str, columns: List[str] = [], sep=','):
Я не знаю, что по кодстайлу, но тут даже нет единообразия. Пробелы вокруг '=' либо ставь, либо не ставь (я за первый вариант).

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +        state = DownloadState.OK
Странно, что ты сетишь OK сразу как только запускаешь. Возможно, тебе не хватает значений.
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskstatus

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +            res = ""
А почему не null\None?

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +class BatchParallelScrapper(BaseScrapper):
А почему два класса в одном файл? Они еще и не сильно связаны.

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +        self.n_jobs = n_jobs
n_jobs? jobs_count? job_index?

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +            while True:
Выглядит не очень. А как это работает?

2021-07-13 06:22 UTC, FrediKats commented on parqser/scrapper/batch.py
> +        [t.join() for t in threads]
Заведи хоть таску на асинхронный запуск.

2021-07-13 06:22 UTC, FrediKats commented on parqser/web_component/base.py
> +class BaseComponent:
Не понимаю, что это за сущность с точки зрения доменной модели. Выглядит как... хелпер-класс с методов перевода в снейк? Возможно, это их-ха того, что он частично NotImplemented, но стоит подумать над неймингом и зоной ответственности этого класса.

2021-07-13 07:20 UTC, ARQtty commented on parqser/LICENSE
> +Copyright (c) 2020 Ilya
4 раз переписываю жеж

2021-07-13 07:33 UTC, ARQtty commented on parqser/page/base.py
> +        self._parse_results[param_name] = param_value
если это _parse_parameters, то он должен парсить. А он не парсит, а просто добавляет
Тогда мб _parsed_parameters?

2021-07-13 07:33 UTC, ARQtty commented on parqser/parser/base.py
> +class BaseParser:
в питоне в целом ок писать много классов в одном файле, поэтому скорее нет

2021-07-13 07:33 UTC, ARQtty commented on parqser/parser/base.py
> +    def parse(self, page: BasePage) -> BasePage:
Разве не правильно будет использовать общего предка всех Page'ей, чтобы параметр был валидным для любого наследника BasePage?

2021-07-13 07:33 UTC, ARQtty commented on parqser/parser/base.py
> +    @classmethod
@anything можно назвать аннотацией и декоратором

почему классы объектов должны выглядеть одинаково? Объекты же разные, разная логика, разные требования к архитектуре

2021-07-13 07:33 UTC, ARQtty commented on parqser/saver/csv.py
> +    def __init__(self, path: str, columns: List[str] = [], sep=','):
меня это тоже триггерит, но линтер требует именно такого :(

2021-07-13 07:33 UTC, ARQtty commented on parqser/saver/csv.py
> +    def _validate_file_columns(self, path: str, sep: str, columns: List[str]) -> Union[None, List[str]]:
(((((((((((((

2021-07-18 09:06 UTC, ARQtty commented on parqser/saver/csv.py
> +    def _validate_file_columns(self, path: str, sep: str, columns: List[str]) -> Union[None, List[str]]:
есть две самых популярных либы работы с csv: дефолтная csv и pandas. У обеих методы чтения и записи файлов используют аргумент sep для сепаратора

2021-07-18 09:06 UTC, ARQtty commented on parqser/saver/csv.py
> +    def _validate_file_columns(self, path: str, sep: str, columns: List[str]) -> Union[None, List[str]]:
я не бедный, я просто следую конвенции...(((

2021-07-18 09:06 UTC, ARQtty commented on parqser/saver/csv.py
> +            if len(columns):
так принято. зачем писать if 0 == 0, если при проверке условие кастуется к bool, а bool(0) == False. ЭКОНОМИТСЯ ЦЕЛЫХ 4 (== 0) СИМВОЛА. БЕСПЛАТНО МОЖНО БУДЕТ НАПИСАТЬ 4 СИМВОЛА В ДРУГОМ МЕСТЕ

2021-07-18 09:06 UTC, ARQtty commented on parqser/scrapper/batch.py
> +            res = ""
потому что результат скачивания - строка с html. Если ничего не скачалось, то ничего не должно распарситься. В то же время программа не должна упасть на парсинге. 
Добавлять в парсинг проверку на null - запихивание логики скачивания в парсинг, что нехорошо. А если для failed страниц возращать пустую строку, то выглядит норм

2021-07-18 09:06 UTC, ARQtty commented on parqser/scrapper/batch.py
> +class BatchParallelScrapper(BaseScrapper):
К сожалению, многопоточку нужно наследовать от Thread. Чтобы сделать батчевую загрузку, нужно делать многопоточную загрузку. Поэтому второй класс тут. Насколько я знаю, в питоне нет требования к одному классу в одном файле (хотя в питоне и типы не указывают, но как стало хорошо, когда я указал. Возможно и по классу на файл будет приятно)

2021-07-18 09:06 UTC, ARQtty commented on parqser/scrapper/batch.py
> +        self.n_jobs = n_jobs
как и с sep: в популярных либах n_jobs используют для количества потоков. Что выбрать между известной конвенцией и своим видением трактуемости?

2021-07-18 09:06 UTC, ARQtty commented on parqser/scrapper/batch.py
> +            while True:
сама функция - итератор. Внутри неё `iter` делает из списка url'ов итератор. `islice` достает из итератора n объектов, пока это возможно. То есть достает батч размера <=n. `yield` это команда возврата объекта из итератора (чтобы можно было писать `for batch in batch_urls([...]):`)
 StopIteration - это и правда некоторый костыль. Без него ошибка не ловится

2021-07-18 09:06 UTC, ARQtty commented on parqser/scrapper/batch.py
> +        [t.join() for t in threads]
отдельный метод?..

2021-07-18 09:06 UTC, ARQtty commented on parqser/web_component/base.py
> +class BaseComponent:
задумывалось это как метод, от которого будут создавать наследовать конкретные классы компонент-парсеров. Возможно следует создать NamedComponent, где будет логика выяснения имени, и уже от него наследовать BaseComponent?

2021-07-18 09:06 UTC, merged